# -*- coding: utf-8 -*-
"""codigo_para_cargar_db_1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H3oI2FipCugEl87TfWi4b2vTXt7FyViT
"""

from google.colab import files
uploaded = files.upload()
import pandas as pd
import io

# Get the actual filename from the uploaded dictionary
# list(uploaded.keys()) will give you a list of the uploaded filenames
# Use the correct filename based on your uploaded file
actual_filename = list(uploaded.keys())[0]  # Assuming you uploaded only one file

# Now use the actual filename to read the CSV
df = pd.read_csv(io.BytesIO(uploaded[actual_filename]), encoding="latin-1")

# Ver las primeras 5 filas
df.head()