LINK A LOS MEDIOS DE PUBLICACIÓN

## MEDIOS

https://www.biobiochile.cl/...

https://www.lun.com/...

https://twitter.com/...

https://www.meganoticias.cl/...

https://www.publimetro.cl/...

https://www.cooperativa.cl/...

https://www.biobiochile.cl/...

## CNTV
https://cntv.cl/historial/