# -*- coding: utf-8 -*-
"""codigo_para_cargar_db_1_TRM

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16VP6z-AqhYuI-ECAvboufMe1soKmT31G
"""

import pandas as pd
from google.colab import files

# Upload the file
uploaded = files.upload()

# Get the filename from the uploaded dictionary
filename = list(uploaded.keys())[0]  # Assuming only one file is uploaded

# Cargar el archivo CSV using the filename
df = pd.read_csv(filename)

# Ver las primeras 5 filas
df.head()