# -*- coding: utf-8 -*-
"""codigo_para_cargar_db_1_CB

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W6hmjjM6AX0Eqloj5LWMIvrvMdBHG8u8
"""

from google.colab import files
uploaded = files.upload()
import pandas as pd
import io

# Get the actual filename from the uploaded dictionary
uploaded_filename = list(uploaded.keys())[0]

# Load the CSV file using the correct filename
df = pd.read_csv(io.BytesIO(uploaded[uploaded_filename]))

# View the first 5 rows
df.head()